-ssid=wirelessnetname
-psk=wirelessnetpassword
-pipass=passwordforpiuser
-enableSsh=false
-disableSsh=false
--bp_INIMAPSRV
imap.gmail.com
--bp_INIMAPACCT
addr@gmail.comx
--bp_INIMAPPASS
passwd
--bp_INDNAME
MyDevName
--bp_DOUPNPFWD
true
--bp_doSetup
false
