
# Start in daemon (background) mode and release terminal (default: off)
daemon off

#pixels to trigger motion event default 1500
threshold 4000
#threshold 10000000000

#def off
threshold_tune on

#def 32
noise_level 64

#def off
noise_tune on

#despecl for improving pixel detection (dropping specs) def none
despeckle EedDl

#webcam_localhost off
#webcam_port 8990

#for http control
webcontrol_localhost on

#user:pass for auth, default off
#control_authentication user:pass

#pre captured picframes, default 1
pre_capture 0

#webcontrol_port 8890
#videodevice /dev/video0
#target_dir cam0
